### PR TITLE
Iterating typed fields cleanup

### PR DESCRIPTION
**Pull request by chisholm**
The code for iterating over TypedFields was bugging me.  There was copy-pasted code that searched `__mro__`, duplicate functionality in _get_vars(), ... I'm guessing some of this is very old code, written before better ways of doing things were known.

I made a small change to replace _get_vars() with a typed_fields property which returns a generator over all TypedFields in an entity.  All TypedField iterating code now just uses the property.  _get_vars() was a classmethod, but it was never used anywhere that required access as a classmethod.  If it ever becomes necessary, I can switch it back.

There will be a related, very small pull request in python-cybox too.  All nosetests still pass.

### CODE REVIEW

**Comment by bworrell** [comment]
@chisholm, that `__mro__` related code came from work surrounding [this discussion](https://github.com/STIXProject/python-stix/issues/163). 

The issue was that the `inspect.getmembers()` call will evaluate the predicate against all class members (including inherited ones) and **never** find any `TypedField` attributes beyond `Entity` in the inheritance chain. 

This means  that there were a lot of unnecessary `isinstance()` calls being performed that would never return `True`. When compounding lots of serializations over many documents, it adds up to a lot of unnecessary computations and time.

Here is an example script that sorta benchmarks the approaches (sorry for the lack of comments, I just sorta banged this out):

```python
import inspect


class Field(object):
    def __get__(self, instance, owner):
        if not instance:
            return self
        return instance._fields[id(self)]

    def __set__(self, instance, value):
        instance._fields[id(self)] = value


class BaseModel(object):
    def __init__(self):
        self._fields = {}


class IntermediateModel(BaseModel):
    x = Field()
    y = Field()


class Model(IntermediateModel):
    foo = Field()
    bar = Field()
    a   = Field()
    b   = Field()
    c   = Field()


MODELS = [Model() for x in xrange(100000)]


def use_inspect():
    fieldcount  = 0

    for object_ in MODELS:
        klass  = object_.__class__
        fields = inspect.getmembers(klass, predicate=lambda x: isinstance(x, Field))
        fieldcount += len(fields)

    assert fieldcount == len(MODELS) * 7


def use_mro():
    fieldcount  = 0

    def mro(klass):
        return [x for x in klass.__mro__ if issubclass(x, BaseModel)]

    def fields(klass):
        return [x for x in vars(klass).itervalues() if isinstance(x, Field)]

    for object_ in MODELS:
        klass  = object_.__class__
        fieldcount += sum(len(fields(x)) for x in mro(klass))

    assert fieldcount == len(MODELS) * 7


if __name__ == "__main__":
    from timeit import Timer
    t_inspect = Timer("use_inspect()", "from __main__ import use_inspect")
    print "use_inspect(): ", t_inspect.repeat(5, 1)

    t_mro = Timer("use_mro()", "from __main__ import use_mro")
    print "use_mro(): ", t_mro.repeat(5, 1)
```

**Sample run with output:**
```
use_inspect():  [1.6623291714513673, 1.7144996105719177, 1.6798635082129603, 1.691161674042803, 1.6861426321689272]
use_mro():  [0.47426486659284883, 0.4888232809952626, 0.4885625219278982, 0.4923864814288983, 0.4772613151759888]
```

**Comment by bworrell** [comment]
@chisholm, i should say that I much prefer the simplicity of the `inspect.getmembers()` approach. It's way **way** cleaner than the `__mro__` traversal stuff :) 

I think we need to consider whether or not the performance bump is worth the hackish code. In that issue I linked above, the biggest improvements came from the way we collected namespace information, so in the grand scheme of things I think the change to `TypedField` collection was less beneficial.

Also, I haven't benchmarked your PR yet, but I'm curious to see how it compares with the existing approach.

**Comment by chisholm** [comment]
Well, that was certainly non-obvious... uncommented hackish code is probably not going to look like other than plain old hackishness to most people who look at it.

Yeah, a benchmark that directly tests what was really at issue, which was XML generation speed with namespaces/schemalocs, would be better.  You posted your test app in that thread, maybe that could be repurposed to test cybox instead of stix.  Need to find the biggest cybox document you can...

Anyway, even if the performance difference matters, why paste the same code twice and still have a method that does the same thing in a different way?  Why test both for isdatadescriptor and a TypedField in _get_vars()?  A TypedField can't be anything else.  Is that another performance optimization?

**Comment by chisholm** [comment]
So I wrote up a benchmark similar to yours (from the old STIXProject/python-stix#163 issue).  It uses the biggest cybox sample XML document from the set of sample documents downloadable from the cybox website.  The timings I got:

master branch(es):
[2.7554267721615266, 2.7503331079013007, 2.7483067855041705, 2.7488947415687495, 2.7528473165340657]
iter_typed_fields_cleanup branch(es):
[3.3213715064907934, 3.323166165401132, 3.2974130299714632, 3.311279116013189, 3.287170718028513]

So the difference is maybe half a second over 400 iterations, or 0.00125 seconds per iteration.  Maybe not that big a deal?

```python
#!/usr/bin/env python
from cybox.core import Observables
import cybox.bindings.cybox_core as core_binding

FN = r"C:\path\to\CybOX_Iran-Oil_Dynamic.xml"
print "[-] Parsing", FN

OBSERVABLES = Observables.from_obj(core_binding.parse(FN))

def test_cybox_to_xml():
    foo = OBSERVABLES.to_xml()

if __name__ == "__main__":
    from timeit import Timer
    t = Timer("test_cybox_to_xml()", "from __main__ import test_cybox_to_xml")
    print "test_cybox_to_xml: ", t.repeat(5, 400)
```

**Comment by bworrell** [comment]
@chisholm 

> Anyway, even if the performance difference matters, why paste the same code twice and still have a method that does the same thing in a different way?

No good answer unfortunately. Just rushing to get something faster in place and finished quickly. A perfect storm!

> Why test both for isdatadescriptor and a TypedField in _get_vars()? A TypedField can't be anything else. Is that another performance optimization?

Again, no great answer here :D

**Comment by bworrell** [comment]
@chisholm, take a look at my [`bw-iter_typed_fields_cleanup`](https://github.com/CybOXProject/mixbox/compare/bw-iter_typed_fields_cleanup) branch and tell me what you think. I took your property, made it lazily store the typed fields so that the `inspect.getmembers()` call is only executed once during the lifetime of the object. 

I also changed the way that `TypedField` stores data on an `Entity`. Rather than using it's `name` attribute value as the `_fields` key, I store `self` as the key. This way, `Entity` doesn't need to find and iterate over all its `TypedFields` during serialization--it only needs to look at it's internal `_fields` member. @gtback, can you see any issues with this approach?

Here is the Iran Oil benchmark with these updates:
```
(python-cybox) C:\dev\mixbox>python bench.py
test_iran_oil:      [2.6474972355802584, 2.6587461147026077, 2.6512535774005217, 2.684458164227629, 2.6566292286879296]
```

I actually found some bugs in python-cybox through work on this branch, so I pushed changes to `master` and `iter_typed_fields_cleanup` branches there. Once I made those changes, the unit tests passed.

**Comment by chisholm** [comment]
I don't see any issues with it.  I'm happy with it.  Timings are in the 2.25-2.3 sec range on my laptop.

**Comment by bworrell** [comment]
@chisholm, cool! I just merged my changes into this branch.

**Comment by bworrell** [comment]
This all looks cool to me. Merging!

**Pull request merged**
