### PR TITLE
Added signals module

### PR DESCRIPTION
**Pull request by bworrell**
Added a a `mixbox.signals` module which provides methods for registration of signal handlers, as well as the code necessary to emit signal.

My thought is that we could alter our `Entity` parse/serialization code to support the registration of event handlers:

(a terrible) Example:
```python
from mixbox import signals

class Indicator(...):

    @classmethod
    def from_obj(cls, obj, return_obj=None):

        if return_obj is None:
            return_obj = cls()

       # Parse the binding object
        
        signals.emit("post.from_obj", return_obj, obj)
        return return_obj
```

```python
from mixbox import signals
from stix.indicator import Indicator

@signals.handler("post.from_obj")
def alter_id(api, binding):
    """Append message to each Indicator ID."""
    if isinstance(api, Indicator) and api.id_:
        api.id_ += "_altered_by_signal_handler"

````

### CODE REVIEW

**Comment by bworrell** [comment]
@gtback, after we talked I made the following changes:
* Renamed `events` to `signals`
* Removed the signal constants (we can add some later as we start to use signals)
* Added a unit test (more to come!)

**Comment by gtback** [comment]
Looks good. Merging!

**Comment by gtback** [comment]
FYI, I rebased the merge commit out of the master branch, so ead16fdfc73b3eaf3e4141c7335a4d96324d2c7a is no longer in master. Just to keep a linear history

**Comment by ikiril01** [comment]
:+1:

We need to start naming more modules after Rush albums! http://en.wikipedia.org/wiki/Signals_(Rush_album)

**Pull request merged**
